jupyter:
  image: jupyter/scipy-notebook
  ports:
    - "8888:8888"
  volumes:
    - sciencedata:/code
  links:
    - db
db:
  image: mongo
  volumes: 
    - sciencedata:/data/db
    - sciencedata:/data/configdb
